# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.18.4

# Mod Properties
mod_version=4.1.7+26.1
maven_group=walksy.shieldstatus
archives_base_name=ShieldStatus

# Dependencies
fabric_version=0.145.2+26.1.1
walksylib_version=1.0.10+26.1


